name: Windows Binary Release

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Binary (Release Mode)
        run: cargo build --release

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/binwalk.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
